# Generated by Django 3.2.9 on 2021-11-20 16:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EANKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='EAN-13')),
                ('use', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('second_name', models.CharField(max_length=255, verbose_name='Фамилия пользователя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения')),
                ('EAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.eankey', verbose_name='EAN-13')),
            ],
        ),
    ]
